### ISSUE TITLE
clear button for maze is not working properly 

### ISSUE THREAD

**Issue by wizard00** [kandebonfim/keep-talking-and-nobody-explodes#2]
It will not clear the red triangle and dot. Also, after clear, it will not be able to choose the circle position

**Comment by kandebonfim** [comment]
@wizard00 good catch. I was working on it when my notebook got broken. Lol. It's done now! https://github.com/kandebonfim/keep-talking-and-nobody-explodes/commit/a1db313546093c409b1d6406eb74d83a5da0895a Already on production.
